server:
  port: 9090

spring:
  application:
    name: file-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://30.21.134.231:3306/file_management?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Phoebus_iot_!cloud#1
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      pool-prepared-statements: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis-plus:
  type-aliases-package: com.fia.file.entity
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      id-type: auto
